apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: an0qh8h48-python 
  janus-idp.io/tekton: an0qh8h48-python
  backstage.io/kubernetes-id: an0qh8h48-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: an0qh8h48-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml